Repository pashagolub/pgxmock, pull requests merged in 2022-11, with the labels that each got.

#113 [-] fix `Scan()` panic if nullable `sql` types used, fixes #102
  .golangci.yml
  rows.go
  sql_test.go
Labels: bug, test

#115 [+] make arguments matching using `WithArgs` mandatory, fixes #114
  expectations.go
  expectations_test.go
  pgxmock_test.go
Labels: enhancement

#117 [*] remove `pgxIface.BeginTxFunc()` as deprecated, closes #111
  examples/basic/basic.go
  examples/basic/basic_test.go
  pgxmock.go
Labels: bug
