Repository pashagolub/pgxmock, pull requests merged in 2023-03, with the labels that each got.

#131 [*] docs: update comment to include option to match out of order
  pgxmock.go
Labels: documentation

#132 [-] fix `context.Context` use in methods
  driver.go
  pgxmock.go
Labels: bug

#134 [*] update `ExpectCopyFrom()` definition to match `CopyFrom()`, closes #127
  expectations.go
  expectations_test.go
  pgxmock.go
  pgxmock_test.go
Labels: enhancement
