Repository pashagolub/pgxmock, pull requests merged in 2024-08, with the labels that each got.

#216 [-] fix panic for double unlock for unexpected method calls
  pgxmock.go
Labels: bug

#217 [+] add test case for double unlock
  pgxmock_test.go
Labels: test

#219 [-] fix `govet` linter warning
  go.mod
  go.sum
  pgxmock.go
Labels: chore
